import { createThemeContract } from "@vanilla-extract/css";

export const semanticColorsContract = createThemeContract({
  // semantic colors
  primary: {
    primary1: null,
    primary2: null,
    primary3: null,
    primary4: null,
    primary5: null,
    primary6: null,
    primary7: null,
    primary8: null,
    primary9: null,
    primary10: null,
    primary11: null,
    primary12: null,
  },
  primaryA: {
    primaryA1: null,
    primaryA2: null,
    primaryA3: null,
    primaryA4: null,
    primaryA5: null,
    primaryA6: null,
    primaryA7: null,
    primaryA8: null,
    primaryA9: null,
    primaryA10: null,
    primaryA11: null,
    primaryA12: null,
  },
  primaryTextContrast: null,

  secondary: {
    secondary1: null,
    secondary2: null,
    secondary3: null,
    secondary4: null,
    secondary5: null,
    secondary6: null,
    secondary7: null,
    secondary8: null,
    secondary9: null,
    secondary10: null,
    secondary11: null,
    secondary12: null,
  },
  secondaryA: {
    secondaryA1: null,
    secondaryA2: null,
    secondaryA3: null,
    secondaryA4: null,
    secondaryA5: null,
    secondaryA6: null,
    secondaryA7: null,
    secondaryA8: null,
    secondaryA9: null,
    secondaryA10: null,
    secondaryA11: null,
    secondaryA12: null,
  },
  secondaryTextContrast: null,

  error: {
    error1: null,
    error2: null,
    error3: null,
    error4: null,
    error5: null,
    error6: null,
    error7: null,
    error8: null,
    error9: null,
    error10: null,
    error11: null,
    error12: null,
  },
  errorA: {
    errorA1: null,
    errorA2: null,
    errorA3: null,
    errorA4: null,
    errorA5: null,
    errorA6: null,
    errorA7: null,
    errorA8: null,
    errorA9: null,
    errorA10: null,
    errorA11: null,
    errorA12: null,
  },
  errorTextContrast: null,

  // success: ,
  // warning: ,
  // info: ,

  background: null,
  backgroundTextContrast: null,

  surface: null,
  surfaceTextContrast: null,

  transparentSurface: null,
  transparentSurfaceTextContrast: null,

  textSubtle: null,
  textPlaceholder: null,

  /** Dividers, outlines etc. */
  line: null,

  transparentHover: null,
  transparentActive: null,
});
