name: tests

on:
  pull_request:
    branches: main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code repository
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10
          cache: true

      - name: Setup node.js 26
        uses: actions/setup-node@v6
        with:
          node-version: 26

      - name: Install dependencies
        run: pnpm i

      - name: Lint
        run: pnpm --filter "[origin/main]" lint

      - name: Build
        run: pnpm --filter "[origin/main]" build

      - name: Test
        run: pnpm --filter "[origin/main]" test
